### ISSUE TITLE
No completion for local variables

### ISSUE THREAD

**Issue by abc123098123** [xcwen/ac-php#58]
It seems there is not completion for local variables.

For example:

```
<?php
$test = time();
$te|
?>
```

It doesn't complete the variable $test.

Here is my [init.el](https://pastebin.com/raw/kF4CSc3G) .

**Comment by xcwen** [comment]
yes , it's not supported

**Comment by ghost** [comment]
I solved this by using `(add-to-list 'ac-sources 'ac-source-php)` instead of `(setq ac-sources '(ac-source-php))` so I get auto-completion from more than just `ac-php`. Would be neat if ac-php supported local variable completion. If you click `M-/` and `dabbrev-expand` or `hippie-expand` you will probably get completion of local variable names, I find `hippie-expand` very useful for repeating code snippets.

**Comment by abc123098123** [comment]
Well, I'll try to figure it out with company.

Thank you.
